### PR TITLE
Add wholesale domain origin

### PR DESCRIPTION
**Pull request by BjarkeMeier**
## References

* #0000

### CODE REVIEW

**Comment by FirestarJes** [comment]
Wouldn't it be more appropriate to jsut rename the aggregations enum to wholesale instead of adding wholesale to the list of domains? As i've understood it, aggreagations is wholesale correct?

**Comment by BjarkeMeier** [comment]
> Wouldn't it be more appropriate to just rename the aggregations enum to wholesale instead of adding wholesale to the list of domains? As i've understood it, aggreagations is wholesale correct?

Sure if that works for you. Fixed.

**Comment by FirestarJes** [comment]
We've looked a bit further into this, and we also use a similar enum on the internal MessageHub side of this, which would also require renaming. We also have other functions with the naming of aggregations...

So we should probably reconsider whether we want to rename all the places that currently uses the aggregations name, or perhaps add it as a new domain as first suggested.

I will discuss this with the team as soon as possible and i'll get back to you when we have decided on a course of action.

**Review by FirestarJes — CHANGES_REQUESTED** [review]
As i wrote in the comment, this is not enough to make this change. Since this enum is parsed in the main  MessageHub project, so requires changes in that domain also.

No further work should be done on this until we have discussed the proper way of handling this change.

**Comment by defectiveAi** [comment]
Too many changes to codebase since PR was made. Another PR will be used instead: https://github.com/Energinet-DataHub/geh-post-office/pull/781

**Pull request closed without merging**
