### PR TITLE
Update MessageHub to send guids using Blob Storage

### PR DESCRIPTION
**Pull request by defectiveAi**

### CODE REVIEW

**Comment by defectiveAi** [comment]
@Renetnielsen @djorgensendk We now need Azurite to run the tests, but adding the flag is not enough. Must best guess is that I also have to bump the version to @2.0.0, but unsure of consequences. And do I have to update all the workflows, or just the dotnet-solution-ci.yml.

**Comment by Renetnielsen** [comment]
> @Renetnielsen @djorgensendk We now need Azurite to run the tests, but adding the flag is not enough. My best guess is that I also have to bump the version to @2.0.0, but unsure of consequences. And do I have to update all the workflows, or just the dotnet-solution-ci.yml?

@dstsyst Can u please help enlighten this young gentleman :) - You prolly have the best perspective of this

**Review by Renetnielsen — DISMISSED** [review]

**Review by FirestarJes — DISMISSED** [review]

**Review by michaelmajgaard — DISMISSED** [review]

**Comment by defectiveAi** [comment]
Waiting for https://github.com/Energinet-DataHub/geh-post-office/pull/376 and version bump.

**Comment by defectiveAi** [comment]
Do not complete until Fri 26., after System Demo.

**Review by FirestarJes — APPROVED** [review]

**Review by xnetsrak — APPROVED** [review]

**Pull request merged**
